// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable identifier_name type_name file_length
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: MenuItem.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// protoc --swift_out=. MenuItem.proto

import Foundation
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct MenuItemCache {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var timeout: Double = 0

    var created: Double = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct MenuItemList {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var items: [MenuItem] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct MenuItem {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var pathIndices: String = .init()

    var shortcut: String = .init()

    var path: [String] = []

    var searchPath: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct AlfredResultList {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var items: [AlfredResultItem] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct AlfredResultItem {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var title: String = .init()

    var subtitle: String = .init()

    var arg: String = .init()

    var uid: String = .init()

    var autoComplete: String = .init()

    var valid: Bool = false

    var icon: AlfredResultItemIcon {
        get { return _icon ?? AlfredResultItemIcon() }
        set { _icon = newValue }
    }

    /// Returns true if `icon` has been explicitly set.
    var hasIcon: Bool {
        return _icon != nil
    }

    /// Clears the value of `icon`. Subsequent reads from it will return its default value.
    mutating func clearIcon() {
        _icon = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _icon: AlfredResultItemIcon?
}

struct AlfredResultItemIcon {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var type: String = .init()

    var path: String = .init()

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Settings {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var appFilters: [AppFilter] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct AppFilter {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var app: String = .init()

    var ignoreMenuPaths: [MenuPath] = []

    var showDisabledMenuItems: Bool = false

    var showAppleMenu: Bool = false

    var cacheDuration: Double = 0

    var disabled: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct MenuPath {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var path: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

#if swift(>=5.5) && canImport(_Concurrency)
extension MenuItemCache: @unchecked Sendable {}
extension MenuItemList: @unchecked Sendable {}
extension MenuItem: @unchecked Sendable {}
extension AlfredResultList: @unchecked Sendable {}
extension AlfredResultItem: @unchecked Sendable {}
extension AlfredResultItemIcon: @unchecked Sendable {}
extension Settings: @unchecked Sendable {}
extension AppFilter: @unchecked Sendable {}
extension MenuPath: @unchecked Sendable {}
#endif // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension MenuItemCache: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "MenuItemCache"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "timeout"),
        2: .same(proto: "created"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularDoubleField(value: &timeout)
            case 2: try decoder.decodeSingularDoubleField(value: &created)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if timeout != 0 {
            try visitor.visitSingularDoubleField(value: timeout, fieldNumber: 1)
        }
        if created != 0 {
            try visitor.visitSingularDoubleField(value: created, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: MenuItemCache, rhs: MenuItemCache) -> Bool {
        if lhs.timeout != rhs.timeout {
            return false
        }
        if lhs.created != rhs.created {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension MenuItemList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "MenuItemList"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "items"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &items)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !items.isEmpty {
            try visitor.visitRepeatedMessageField(value: items, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: MenuItemList, rhs: MenuItemList) -> Bool {
        if lhs.items != rhs.items {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension MenuItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "MenuItem"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "pathIndices"),
        2: .same(proto: "shortcut"),
        3: .same(proto: "path"),
        4: .same(proto: "searchPath"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &pathIndices)
            case 2: try decoder.decodeSingularStringField(value: &shortcut)
            case 3: try decoder.decodeRepeatedStringField(value: &path)
            case 4: try decoder.decodeRepeatedStringField(value: &searchPath)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !pathIndices.isEmpty {
            try visitor.visitSingularStringField(value: pathIndices, fieldNumber: 1)
        }
        if !shortcut.isEmpty {
            try visitor.visitSingularStringField(value: shortcut, fieldNumber: 2)
        }
        if !path.isEmpty {
            try visitor.visitRepeatedStringField(value: path, fieldNumber: 3)
        }
        if !searchPath.isEmpty {
            try visitor.visitRepeatedStringField(value: searchPath, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: MenuItem, rhs: MenuItem) -> Bool {
        if lhs.pathIndices != rhs.pathIndices {
            return false
        }
        if lhs.shortcut != rhs.shortcut {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.searchPath != rhs.searchPath {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension AlfredResultList: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "AlfredResultList"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "items"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &items)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !items.isEmpty {
            try visitor.visitRepeatedMessageField(value: items, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: AlfredResultList, rhs: AlfredResultList) -> Bool {
        if lhs.items != rhs.items {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension AlfredResultItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "AlfredResultItem"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "title"),
        2: .same(proto: "subtitle"),
        3: .same(proto: "arg"),
        4: .same(proto: "uid"),
        5: .unique(proto: "autoComplete", json: "autocomplete"),
        6: .same(proto: "valid"),
        7: .same(proto: "icon"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &title)
            case 2: try decoder.decodeSingularStringField(value: &subtitle)
            case 3: try decoder.decodeSingularStringField(value: &arg)
            case 4: try decoder.decodeSingularStringField(value: &uid)
            case 5: try decoder.decodeSingularStringField(value: &autoComplete)
            case 6: try decoder.decodeSingularBoolField(value: &valid)
            case 7: try decoder.decodeSingularMessageField(value: &_icon)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !title.isEmpty {
            try visitor.visitSingularStringField(value: title, fieldNumber: 1)
        }
        if !subtitle.isEmpty {
            try visitor.visitSingularStringField(value: subtitle, fieldNumber: 2)
        }
        if !arg.isEmpty {
            try visitor.visitSingularStringField(value: arg, fieldNumber: 3)
        }
        if !uid.isEmpty {
            try visitor.visitSingularStringField(value: uid, fieldNumber: 4)
        }
        if !autoComplete.isEmpty {
            try visitor.visitSingularStringField(value: autoComplete, fieldNumber: 5)
        }
        if valid != false {
            try visitor.visitSingularBoolField(value: valid, fieldNumber: 6)
        }
        try {
            if let v = self._icon {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
            }
        }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: AlfredResultItem, rhs: AlfredResultItem) -> Bool {
        if lhs.title != rhs.title {
            return false
        }
        if lhs.subtitle != rhs.subtitle {
            return false
        }
        if lhs.arg != rhs.arg {
            return false
        }
        if lhs.uid != rhs.uid {
            return false
        }
        if lhs.autoComplete != rhs.autoComplete {
            return false
        }
        if lhs.valid != rhs.valid {
            return false
        }
        if lhs._icon != rhs._icon {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension AlfredResultItemIcon: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "AlfredResultItemIcon"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "type"),
        2: .same(proto: "path"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &type)
            case 2: try decoder.decodeSingularStringField(value: &path)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !type.isEmpty {
            try visitor.visitSingularStringField(value: type, fieldNumber: 1)
        }
        if !path.isEmpty {
            try visitor.visitSingularStringField(value: path, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: AlfredResultItemIcon, rhs: AlfredResultItemIcon) -> Bool {
        if lhs.type != rhs.type {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension Settings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "Settings"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "appFilters"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &appFilters)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !appFilters.isEmpty {
            try visitor.visitRepeatedMessageField(value: appFilters, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Settings, rhs: Settings) -> Bool {
        if lhs.appFilters != rhs.appFilters {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension AppFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "AppFilter"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "app"),
        2: .same(proto: "ignoreMenuPaths"),
        3: .same(proto: "showDisabledMenuItems"),
        4: .same(proto: "showAppleMenu"),
        5: .same(proto: "cacheDuration"),
        6: .same(proto: "disabled"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &app)
            case 2: try decoder.decodeRepeatedMessageField(value: &ignoreMenuPaths)
            case 3: try decoder.decodeSingularBoolField(value: &showDisabledMenuItems)
            case 4: try decoder.decodeSingularBoolField(value: &showAppleMenu)
            case 5: try decoder.decodeSingularDoubleField(value: &cacheDuration)
            case 6: try decoder.decodeSingularBoolField(value: &disabled)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !app.isEmpty {
            try visitor.visitSingularStringField(value: app, fieldNumber: 1)
        }
        if !ignoreMenuPaths.isEmpty {
            try visitor.visitRepeatedMessageField(value: ignoreMenuPaths, fieldNumber: 2)
        }
        if showDisabledMenuItems != false {
            try visitor.visitSingularBoolField(value: showDisabledMenuItems, fieldNumber: 3)
        }
        if showAppleMenu != false {
            try visitor.visitSingularBoolField(value: showAppleMenu, fieldNumber: 4)
        }
        if cacheDuration != 0 {
            try visitor.visitSingularDoubleField(value: cacheDuration, fieldNumber: 5)
        }
        if disabled != false {
            try visitor.visitSingularBoolField(value: disabled, fieldNumber: 6)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: AppFilter, rhs: AppFilter) -> Bool {
        if lhs.app != rhs.app {
            return false
        }
        if lhs.ignoreMenuPaths != rhs.ignoreMenuPaths {
            return false
        }
        if lhs.showDisabledMenuItems != rhs.showDisabledMenuItems {
            return false
        }
        if lhs.showAppleMenu != rhs.showAppleMenu {
            return false
        }
        if lhs.cacheDuration != rhs.cacheDuration {
            return false
        }
        if lhs.disabled != rhs.disabled {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

extension MenuPath: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = "MenuPath"
    static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
        1: .same(proto: "path"),
    ]

    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedStringField(value: &path)
            default: break
            }
        }
    }

    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
        if !path.isEmpty {
            try visitor.visitRepeatedStringField(value: path, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: MenuPath, rhs: MenuPath) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.unknownFields != rhs.unknownFields {
            return false
        }
        return true
    }
}

// swiftlint:enable identifier_name type_name
